server:
  port: 8010

spring:
  datasource:
    username: sa
    password:
    #url: jdbc:h2:file:e:/testdb;INIT=CREATE SCHEMA IF NOT EXISTS USERS;NON_KEYWORDS=KEY
    url: jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS USERS;NON_KEYWORDS=KEY
    driverClassName: org.h2.Driver
    #--url : http://localhost:9090/authentication/h2-console/
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization : true
    init:
      platform: h2
    hibernate:
      ddl-auto: none

  sql:
    init:
      data-locations:
        - classpath:script/h2/tables.sql
        - classpath:script/h2/sequences.sql
        - classpath:script/h2/startData.sql
 #----------- allowed cors origin
cors:
  allowed-origins:
    - http://localhost:3000